sonar.projectKey=transparency-service
sonar.javascript.node.maxspace=8192
sonar.python.coverage.reportPaths=coverage.xml
sonar.test.inclusions=**/tests/**,**/tests_front/**
sonar.exclusions=**/examples/**
